#!/bin/bash
sudo apt-get update
sudo apt-get install -y --force-yes openjdk-6-jre-headless
sudo apt-get install -y vim zip unzip subversion git-core binutils build-essential python-dev python-setuptools python-imaging python-reportlab gdal-bin libproj-dev libgeos-dev python-urlgrabber python-scipy python-nose pep8 python-virtualenv python-gdal python-pastescript gettext libpq-dev postgresql-contrib

if [ ! -d "./venv" ]; then
     echo ">>>> Creating the virtualenv and installing dependencies"
     virtualenv venv
     source venv/bin/activate
     easy_install -U pip
fi

echo ">>>> Activating the virtualenv"
source venv/bin/activate

function checkup() {
  REPO="$1"
  WORKING_DIR="$2"
  if [ -d "${WORKING_DIR}" ];
  then
      echo "Updating ${WORKING_DIR} from upstream"
      (cd "${WORKING_DIR}" && git pull)
  else
      git clone "git@github.com:${REPO}" "${WORKING_DIR}" || git clone "https://github.com/${REPO}" "${WORKING_DIR}"
  fi
}

echo ">>>> Clone/pull from the specified GeoNode repo and branch"
checkup GFDRR/geonode.git geonode
pushd .
pip install -r geonode/shared/core-libs.txt
cd geonode/src/GeoNodePy
python setup.py develop
popd

geonode validate
