# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-26 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_merge'),
        ('base', '0030_resourcebase_created'),
    ]

    operations = [
    ]
